#!MC 1000
$!VarSet |MFBD| = '/home/rasquin/SF/MISCTEST/RunTestPassiveScal/OUTPUT'
$!CREATESLICEZONEFROMPLANE 
  SLICESOURCE = VOLUMEZONES
  FORCEEXTRACTIONTOSINGLEZONE = YES
$!PLOTTYPE = CARTESIAN2D
$!FIELDLAYERS SHOWMESH = NO
$!FIELDLAYERS SHOWBOUNDARY = NO
$!GLOBALCONTOUR 1  VAR = 4
$!CONTOURLEVELS RESETTONICE
  CONTOURGROUP = 1
  APPROXNUMVALUES = 15
$!FIELDLAYERS SHOWCONTOUR = YES
$!GLOBALCONTOUR 1  LEGEND{SHOW = YES}
$!REDRAWALL 
$!RemoveVar |MFBD|
